name: Update GSL Water Data

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pandas

      - name: Run data prep script
        run: python scripts/fetch_gsl_data.py

      - name: Commit and push updated data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add data/gsl_data.json
          git commit -m "Update GSL data" || echo "No changes to commit"
          git push

concurrency:
  group: gsl-data-update
  cancel-in-progress: true

